### ISSUE TITLE
Flask4Edgence之初步修改

### ISSUE THREAD

**Issue by wolfbrother** [EdgeIntelligenceChain/EdgenceHome#1]
#### 目标
+ 删掉注册登录功能，post页面的按钮
+ 前端只展示单页的网页，可以显示图片、文字
+ 后端的数据库一类的功能保留，以后用
+ 至于显示内容、页面美化则不用管

#### 问题
+ 域名在哪个文件设置
+ 访问端口怎么设置

**Comment by wolfbrother** [comment]
牵涉到的文档工作别忘了

**Comment by piaoliangkb** [comment]
## 在Ubuntu上部署该项目

1. 首先需要安装nginx

```
apt install nginx
```

2. 配置nginx配置文件，之后使用

```
vim /etc/nginx/nginx.conf
```

在http模块中加入如下部分：

```
server {
        listen 80;

        location / {
                proxy_pass http://127.0.0.1:8000;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
}
```

其中，listen后表示监听的端口。之后让nginx重新加载配置文件

```
nginx -s reload
```

使用命令<code>nginx -t</code>检查配置文件是否有错误。

3. 切换到项目目录，启动虚拟环境，使用gunicorn启动flask

```
source venv/bin/activate
```

安装gunicorn

```
pip install gunicorn
```

在后台方式启动gunicorn，保证ssh断开后程序也能正常运行

```
nohup gunicorn -w 4 -b 127.0.0.1:8000 start:app &
```

- -w参数表示启动多少个worker处理网络请求
- -b参数表示将flask app绑定到哪个端口，需要与nginx.conf中的proxy_pass一致

4. 测试访问

在浏览器中直接输入网址 http://45.58.54.216 进行访问，默认端口为nginx.conf中设置的80端口。

若要修改端口，则修改nginx的配置文件并重新加载，在ip后加<code>:port</code>的形式访问。

**Comment by piaoliangkb** [comment]
## 关于前端界面的修改

这个web应用使用了python的flask-bootstrap拓展，利用了Jinja2的模板继承机制。项目的所有html文件位于<code>EdgenceHome/app/templates</code>目录中。

### base.html模板文件

<code>base.html</code>是基模板，我们的所有html文件都是从这个基模板继承而来。

在<code>index.html</code>文件中，第一行用来继承当前文件夹中的<code>base.html</code>模板。

```html
{% extends "base.html" %}
```

例如：

我们在<code>base.html</code>文件中定义了上标题栏和下方的copyright字段，那么所有在开头处引用了<code>base.html</code>这个模板的html界面，开头和结尾都会出现标题栏和copyright字段。

base.html中标题栏的定义：

```html
{% block navbar %}
<div class="navbar navbar-default" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand">Edgence</a>
        </div>
        <li class="navbar-collapse collapse">

            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
                
            </ul>
        </div>
    </div>
</div>
{% endblock %}
```

结尾copyright字段的定义：

```html
{% block content %}
.....
<p align="center">Copyright © Edgence Team of BUPT. All Rights Reserved</p>
{% endblock %}
```

### index.html 主页

页面主体内容在page_content区块中，如下所示

```html
{% block page_content %}

...

{% endblock %}
```

若要添加新的javascript文件，需要这么定义scripts区块：

```html
{% block scripts %}
{{ super() }}
<script type="text/javascript" src="my-script.js"></script> 
{% endblock %}
```

**Comment by piaoliangkb** [comment]
项目内容基于：《Flask Web开发：基于Python的Web应用开发实战（第2版）》https://book.douban.com/subject/30293851/

链接: https://pan.baidu.com/s/1F7wk1hTNb6TBcVI0Zs1_oA 提取码: 94t6

**Comment by wolfbrother** [comment]
#### 这个Flask教程挺方便学习的，在线版
+Flask 入门在线教程： https://read.helloflask.com/
