### ISSUE TITLE
浏览器的区块的UTC时间戳的解析应该放在前端来做，而非后端

### ISSUE THREAD

**Issue by wolfbrother** [EdgeIntelligenceChain/EdgenceHome#7]
如果放在后端，那么对UTC时间戳的解析结果，将于网站服务器所在时区有关，与浏览器无关。

然而，不同时区的浏览器，应该显示不同的时间，即UTC时间戳的解析结果。

因此，解析逻辑应该放在前端来做，而非后端。

**Comment by yyrylp** [comment]
已经修改为后端在页面上渲染时间戳，在页面加载时，前端通过moment.js将时间戳转换成为本地时间。

**Comment by wolfbrother** [comment]
加了https之后，moment.js会被阻碍执行，是怎么回事？
+ 打开网址 https://www.edgence.org/explorer/ ，时间戳仍然是Unix时间，并没有转换。
+ 现在采用了HTTPS

**Comment by wolfbrother** [comment]
转换后的时间，只显示年月日时分秒就行了，不用显示月份和所在时区，不然就太长了；另外，年月日显示为2019-05-02，不要May 02 2019，皱着也太长了

**Comment by yyrylp** [comment]
已经修改为http/https自动适配；时间显示格式修改完毕

**Comment by wolfbrother** [comment]
这两天部署一下
