### ISSUE TITLE
区块浏览器细节

### ISSUE THREAD

**Issue by wolfbrother** [EdgeIntelligenceChain/EdgenceHome#8]
+ 难度的单位
+ 交易信息显示页面，Raw transaction的背景是粉红色，很不协调
+ raw transaction信息的格式化输出
```
>>> block = {"_type":"Transaction","locktime":None,"txins":[{"_type":"TxIn","sequence":0,"to_spend":None,"unlock_pk":None,"unlock_sig":"323332"}],"txouts":[{"_type":"TxOut","to_address":"18R7Y9E7sTH3MKoYP8wnxxPPKhwE8XPdPy","value":5000000000}]}

>>> print(json.dumps(block, sort_keys=True, indent=2))
{
  "_type": "Transaction",
  "locktime": null,
  "txins": [
    {
      "_type": "TxIn",
      "sequence": 0,
      "to_spend": null,
      "unlock_pk": null,
      "unlock_sig": "323332"
    }
  ],
  "txouts": [
    {
      "_type": "TxOut",
      "to_address": "18R7Y9E7sTH3MKoYP8wnxxPPKhwE8XPdPy",
      "value": 5000000000
    }
  ]
}
>>>
```

+ 网站两个子页面的风格不一样，怎么解决？

**Comment by wolfbrother** [comment]
显示的区块列表的最新区块，不是实际的最新区块。没发过来？

**Comment by xiayunil** [comment]
当前完成的:
1. 修改实现区块难度单位,修改代码位于base.jina中
2. 全部重构txid.jinja代码,实现tx的格式化输出,以及transaction的自动扩展支持.当前的实现,将transaction中的字段区分为两个组成部分: 不变字段与可能发生变化字段
 - 目前可变字段主要是txin与txout**中**的字段 , jinja将根据字段中内容自动定义渲染,txin与txout字段可以随意增加字段不引起jinja错误
 - 目前认为transaction外部字段不会发生变化,当前字段有 _type locktime txin txout ,
 - txin与txout可能有多个,当前使用jinja动态渲染,当前只有一行,因此只渲染一行,未来多个txin与txout可自动渲染 
3. 修复区块高度的实现,当前浏览器可以查看所有区块(之前创世区块被忽略)
4. 区块支持float精度的时间戳,主要修改dep.ds.block已经dep.utils.Utils中关于区块的定义,以及序列化反序列化支持
 - 由于时间戳由前端渲染,目前对于float与int并不敏感
