### ISSUE TITLE
https原理步骤

### ISSUE THREAD

**Issue by wolfbrother** [EdgeIntelligenceChain/EdgenceHome#9]
稍微描述一下怎么回事、如何做到的

**Comment by cyycy** [comment]
1.下载certbot及certbot nginx插件
 2.在/etc/nginx/conf.d内增加80端口server配置
3. 运行certbot，填写联系邮箱，要申请证书的域名，等待插件完成域名验证
4. 为server增加443端口配置并添加证书
5. 开启强制https，给80端口增加重定向命令
6. 软重启nginx

**Comment by wolfbrother** [comment]
把每一步怎么做的也补上

**Comment by cyycy** [comment]
1.root登录172.106.33.51
2.下载certbot及certbot nginx插件 https://certbot.eff.org/lets-encrypt/ubuntubionic-nginx这里面有安装步骤
3.安装nginx(由于已经有nginx,因此可以直接跳到4，直接对nginx进行配置即可)
4.修改nginx配置文件 在/etc/nginx/conf.d文件内增加80端口server配置
server {
        listen 80;
        sever_name  www.edgence.org;  #www.edgence.org是域名
        location / {
                proxy_pass http://127.0.0.1:8000;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
}
5. 软重启nginx  nginx -s reload
6. 运行certbot   cerbot --nginx 
7. 第一次运行certbot会让你填写联系的邮箱，
选择要申请证书的域名
<img width="1111" alt="159b80bf880e79bdb72eaaed9f9c67c" src="https://user-images.githubusercontent.com/50165164/57294738-2d435380-70fb-11e9-817f-e41ec8c2e4e2.png">
选择开启强制https，给80端口增加重定向命令
<img width="717" alt="bb8498b8e36736798c4d22747d45b3c" src="https://user-images.githubusercontent.com/50165164/57294775-4815c800-70fb-11e9-831a-97f5aa3b8ef9.png">
之后插件会自动为server增加443端口配置并添加证书，最后软重启nginx，完成。

**Comment by wolfbrother** [comment]
收到



可用于iOS的myMail发送


2019年5月7日 星期二 +0800 下午7:10 发件人 notifications@github.com  <notifications@github.com>:
